# Generated by Django 4.2.7 on 2025-12-21 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("experience", models.TextField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "linkedin_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("website_url", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
                "db_table": "profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_email_4b85f2_idx",
            old_name="users_email_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_role_0ace22_idx",
            old_name="users_role_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_created_6541e9_idx",
            old_name="users_created_idx",
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["user"], name="profiles_user_id_29277a_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["created_at"], name="profiles_created_cbafd1_idx"
            ),
        ),
    ]
