# Generated by Django 4.2.7 on 2025-12-21 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("startups", "0002_add_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="StartupInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Startup Interest",
                "verbose_name_plural": "Startup Interests",
                "db_table": "startup_interests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="startup",
            new_name="startups_owner_i_08696e_idx",
            old_name="startups_owner_idx",
        ),
        migrations.RenameIndex(
            model_name="startup",
            new_name="startups_industr_fb10bc_idx",
            old_name="startups_industry_idx",
        ),
        migrations.RenameIndex(
            model_name="startup",
            new_name="startups_stage_855eb1_idx",
            old_name="startups_stage_idx",
        ),
        migrations.RenameIndex(
            model_name="startup",
            new_name="startups_created_832f8f_idx",
            old_name="startups_created_idx",
        ),
        migrations.AddField(
            model_name="startupinterest",
            name="startup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interests",
                to="startups.startup",
            ),
        ),
        migrations.AddField(
            model_name="startupinterest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="startup_interests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="startupinterest",
            index=models.Index(fields=["user"], name="startup_int_user_id_3d1054_idx"),
        ),
        migrations.AddIndex(
            model_name="startupinterest",
            index=models.Index(
                fields=["startup"], name="startup_int_startup_c68366_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="startupinterest",
            index=models.Index(
                fields=["created_at"], name="startup_int_created_2adb1e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="startupinterest",
            unique_together={("user", "startup")},
        ),
    ]
